server:
  port: 9020
  
eureka:
  instance:
    hostname: localhost
    
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/api/v1/department/**
           
            
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/v1/employee/**                                    